//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scada.wpf.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.1.0")]
    internal sealed partial class SetBaykon : global::System.Configuration.ApplicationSettingsBase {
        
        private static SetBaykon defaultInstance = ((SetBaykon)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SetBaykon())));
        
        public static SetBaykon Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.5.100")]
        public string TEA99_IP {
            get {
                return ((string)(this["TEA99_IP"]));
            }
            set {
                this["TEA99_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.5.101")]
        public string DMS_IP {
            get {
                return ((string)(this["DMS_IP"]));
            }
            set {
                this["DMS_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("502")]
        public int TEA99_Port {
            get {
                return ((int)(this["TEA99_Port"]));
            }
            set {
                this["TEA99_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("502")]
        public int DMS_Port {
            get {
                return ((int)(this["DMS_Port"]));
            }
            set {
                this["DMS_Port"] = value;
            }
        }
    }
}
