//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scada.wpf.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class SetGeneral : global::System.Configuration.ApplicationSettingsBase {
        
        private static SetGeneral defaultInstance = ((SetGeneral)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SetGeneral())));
        
        public static SetGeneral Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoReconnectToPLC {
            get {
                return ((bool)(this["AutoReconnectToPLC"]));
            }
            set {
                this["AutoReconnectToPLC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int AutoReconnectPeriod {
            get {
                return ((int)(this["AutoReconnectPeriod"]));
            }
            set {
                this["AutoReconnectPeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoRecordWhenAppStart {
            get {
                return ((bool)(this["AutoRecordWhenAppStart"]));
            }
            set {
                this["AutoRecordWhenAppStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int AutoRecordPeriod {
            get {
                return ((int)(this["AutoRecordPeriod"]));
            }
            set {
                this["AutoRecordPeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AppStartWithWindows {
            get {
                return ((bool)(this["AppStartWithWindows"]));
            }
            set {
                this["AppStartWithWindows"] = value;
            }
        }
    }
}
