//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scada.wpf.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.1.0")]
    internal sealed partial class SetPLC : global::System.Configuration.ApplicationSettingsBase {
        
        private static SetPLC defaultInstance = ((SetPLC)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SetPLC())));
        
        public static SetPLC Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Profinet_CpuRock {
            get {
                return ((int)(this["Profinet_CpuRock"]));
            }
            set {
                this["Profinet_CpuRock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Profinet_Slot {
            get {
                return ((int)(this["Profinet_Slot"]));
            }
            set {
                this["Profinet_Slot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.5.10")]
        public string Profinet_IP {
            get {
                return ((string)(this["Profinet_IP"]));
            }
            set {
                this["Profinet_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int Profinet_TimeOut {
            get {
                return ((int)(this["Profinet_TimeOut"]));
            }
            set {
                this["Profinet_TimeOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Profinet_Interval {
            get {
                return ((int)(this["Profinet_Interval"]));
            }
            set {
                this["Profinet_Interval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Siemens S7 1200")]
        public string Profinet_DeviceName {
            get {
                return ((string)(this["Profinet_DeviceName"]));
            }
            set {
                this["Profinet_DeviceName"] = value;
            }
        }
    }
}
