//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scada.wpf.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class SetUser : global::System.Configuration.ApplicationSettingsBase {
        
        private static SetUser defaultInstance = ((SetUser)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SetUser())));
        
        public static SetUser Default {
            get {
                return defaultInstance;
            }
        }
    }
}
