//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EldorST18.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public long User_ID { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public bool SuperUser { get; set; }
        public bool Enable { get; set; }
        public Nullable<short> Authorization { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string SecondName { get; set; }
        public string Surname { get; set; }
        public string Title { get; set; }
        public string Position { get; set; }
        public string PhotoAddress { get; set; }
        public string CardID { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    }
}
